### ISSUE TITLE
Input issues

### ISSUE THREAD

**Issue by weloxux** [sickdev/sick#2]
After leaving SICK open without using it for a while, the first message you type does not get sent to the server. No errors are displayed.

**Comment by nessowski** [comment]
On 2015-05-30 14:08, Weloxux wrote:
> After leaving SICK open without using it for a while, the first
> message you type does not get sent to the server. No errors are
> displayed.
> 
> --
> Reply to this email directly or view it on GitHub [1].
> 
> 	*
> 
> Links:
> ------
> [1] https://github.com/Weloxux/sick/issues/2

HEY WELOXUX


I DON'T GIVE A FUCK

**Comment by weloxux** [comment]
No longer relevant after rewrite
